# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='input_interval',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
