# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-17 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190916_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatafield',
            name='final_value',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formdatafield',
            name='initial_value',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
